### ISSUE TITLE
[BUG] Iris Sensor does not work

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/hadesRom_Reports#1]
**Describe the bug**
Iris Sensor in lockscreen and in hwtest does not work

Iris settings has also been removed due to that

**Smartphone (please complete the following information):**
 - All models

**Additional context**
Iris sensor when enrolling lights up and kills it self right away due to issues with TLC and security

**Comment by ChrisLatham** [comment]
I believe this issue is preventing the HSBC UK banking app from working.

Whenever I open the app the phone reboots after a few seconds.

The last entries in Logcat before the device reboots are all regarding the IrisService.

This is a bit of a pain because I can't log into HSBC at all without the app. Bit of a design flaw from HSBC if you ask me, but there we go.

**Comment by Snowers96** [comment]
Wait! I have an S8 and Iris Sensor work very well!! Also, on my banking app work

**Comment by ananjaser1211** [comment]
> I believe this issue is preventing the HSBC UK banking app from working.
> 
> Whenever I open the app the phone reboots after a few seconds.
> 
> The last entries in Logcat before the device reboots are all regarding the IrisService.
> 
> This is a bit of a pain because I can't log into HSBC at all without the app. Bit of a design flaw from HSBC if you ask me, but there we go.

you could try to remove iris xmls from system/etc/permissions and the removing the SecIrisService which would remove iris capabilities from apps, but it will make settings > biometrics take longer to open

i am not sure why the bank app is calling iris directly, so its a bit weird, but thats what i would do if i was in the same situation

**Comment by ChrisLatham** [comment]
[android-debug.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/6116581/android-debug.txt)
[CrashReport.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/6116582/CrashReport.txt)

I have managed to gather the logcat logs from the moment the app starts until it reboots, as well as a crash report.

**Comment by ananjaser1211** [comment]
iris has been resolved in V2.
