### ISSUE TITLE
[BUG] No charging sound

### ISSUE THREAD

**Issue by Hidden-Help** [ananjaser1211/hadesRom_Reports#10]
**Describe the bug**
There is no charging sound when charger is connected. 

**Logs** 
[Note8,No charging sounds.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5745021/Note8.No.charging.sounds.zip)

**To Reproduce**
1. Connect the charger in the phone.
2.You'll not hear any sound when the charger is connected.

**Expected behavior**
A sound that indicates the charger is connected properly and is charging.

**Screenshots**
Can't SS the silence.

**Smartphone (please complete the following information):**
 - Device: [All 8895 phones]
 - Model: [Ctrl+V]

**Additional context**
- Thank you for your work.

**Comment by corsicanu** [comment]
Will be fixed in next release, leaving it open for visibility.
