### ISSUE TITLE
[BUG] QR Scanner camera mode missing

### ISSUE THREAD

**Issue by Mikel0420** [ananjaser1211/hadesRom_Reports#100]
Describe the bug
The QR code recognition is missing.

To Reproduce
If you go into the camera and point at the QR code nothing happens.

Screenshots
YES

![WhatsApp Image 2021-09-17 at 1 35 32 AM](https://user-images.githubusercontent.com/90865244/133666613-e89ed668-d820-46b8-bf4c-9be0b8893dbc.jpeg)

Smartphone (please complete the following information):
All supported

Additional context
No logs needed

Need to dev fixed this bugs, thanks friend

**Comment by Mikel0420** [comment]
if i turn off bixby during installation what is the other way besides installing 3rd party apps? please i need the answer

**Comment by ananjaser1211** [comment]
As mentioned here https://github.com/ananjaser1211/hadesRom_Reports/issues/30#issuecomment-753479366

there is no workaround currently aside from bixby vision, or 3rd party software. i will be closing this since it is a duplicate
