### ISSUE TITLE
[BUG] taking pictures with more 4x zomm

### ISSUE THREAD

**Issue by juuushiro** [ananjaser1211/hadesRom_Reports#101]
**Describe the bug**
wen you zoom in to take pictures, they will be green and read

**To Reproduce**
1. Go to '.camara..'
2. Click on '.make zoom...'
3. Scroll down to '..take photo..'

**Expected behavior**
red green photo

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**

 - Model: [e.g. G950F/ds]
 Samsung Note 8

**Additional context**

**Comment by ananjaser1211** [comment]
This will be fixed with v2.1 , issue was telephoto was kinda busted one way or another

**Comment by juuushiro** [comment]
thx *.* :)

AnanJaser ***@***.***> escreveu no dia sábado, 18/09/2021
à(s) 00:34:

**Comment by workonfire** [comment]
The camera also hangs sometimes and shows an error after a few seconds.

_Server error. Restart the app._

![Screenshot_20211014-135247_Camera.jpg](https://user-images.githubusercontent.com/34654573/137327750-a53d2632-b2b3-49e1-91e3-7a796689e075.jpg)

**Comment by workonfire** [comment]
Also, I don't know whether should I create a new issue for this or not, but there is another problem with the interface itself. It overlaps and sometimes it's really hard to navigate through it. ![Screenshot_20211016-163702_Camera.jpg](https://user-images.githubusercontent.com/34654573/137591719-ac943e93-cd11-417f-af2b-6cd65307cf02.jpg)

**Comment by corsicanu** [comment]
@workonfire what dpi you use?

**Comment by workonfire** [comment]
> @workonfire what dpi you use?

The default value for S8+. I believe it's 411.

**Comment by ananjaser1211** [comment]
All good on my end, not sure why its broken for you

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
