### ISSUE TITLE
[BUG] App Lock Feature removed - previously locked apps remain locked

### ISSUE THREAD

**Issue by SanabilQureshi** [ananjaser1211/hadesRom_Reports#103]
Hi,

Thanks so much for the updated hadesrom, it is really good!

Unfortunately, the App Lock feature has been removed and any apps which I had previously locked before updating continue to be locked without me being able to remove this feature over them.

I used to find the App Lock page in Settings > Advanced Features > App Lock, but the only remnant of it is an installed app with that name - which cannot be removed or disabled. This feature is not the same as Secure Folder by the way.

I would really appreciate either a fix to remove the feature entirely, so I can remove the lock over apps from the last Hades rom, or if you could add it back that would be even better.

Thank you

**Comment by ananjaser1211** [comment]
Hope i am not too late, indeed applock got broken in V2, however you can bring it back. but it will take few edits
you need to use any root file explorer to edit 

system/odm/etc/omc/[yourcountrycode]/conf/cscfeature.xml

find the line `CscFeature_Common_ConfigYuva`

replace the contents inside with `MemorySaver|MemorySaver_Refresh|MemorySaver_Refresh_INSTALL_TO_SDCARD`

save the edited file and reboot, applock will work again.

**Comment by SanabilQureshi** [comment]
Is there any solution which would avoid rooting? I don't mind reflashing again if it is possible to edit this file on a PC and then re-zip the rom for flashing (like the META-INF solution).

**Comment by corsicanu** [comment]
@SanabilQureshi just wait for few days, we will wrap soon v2.1 with fixes to most common v2.0 issues.

**Comment by SanabilQureshi** [comment]
Got it, I'm perfectly happy to wait - thanks once again for all the hard work put in!

**Comment by Snowers96** [comment]
You don´t need to wait, you can launch App Lock with activity launcher from Play Store, just launch AppLock activity :)

**Comment by SanabilQureshi** [comment]
Thank you, I look forward to the v2.1 release :)

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
