### ISSUE TITLE
[Feature] Advanced Charging Controller (ACC) Kernel integration

### ISSUE THREAD

**Issue by Trasher29** [ananjaser1211/hadesRom_Reports#104]
It would be great if the battery idle mode could be enabled in the kernel. That way, VR-25's Advanced Charging Controller (ACC) (https://github.com/Magisk-Modules-Repo/acc) can access the feature and provide great battery control. 

![Screenshot_20210919-235309_AccA](https://user-images.githubusercontent.com/61657523/133944346-60e613fe-7075-4c5a-ad0d-cc5a84fa3938.jpg)

The app for the ACC: https://github.com/mattecarra/acca/releases

I have already seen a similar feature in A2N's kernel app:
![grafik](https://user-images.githubusercontent.com/61657523/133942225-5598948b-c1cd-42e4-a81f-1c61afc8bb71.png)
https://forum.xda-developers.com/t/kernel-9-a2n-kernel-10h-sot-easy-guide-step-by-step-2021-06-03.3875640/
https://github.com/ace2nutzer/Samsung_dreamlte_Kernel

I use a Galaxy S8 and use hadesRom Q v2.0 for Exynos S8

**Comment by ananjaser1211** [comment]
I dont think this is a feature i would know how to implement, the kernel A2N you linked has a fully custom charger controller which interfaces with their kernel application. battery_idle does not seem to be a single drop feature, but one that depends on other features of this charging controller.

I prefer to keep charging behavior (atleast kernel wise) as stock as possible to avoid any protentional issues

**Comment by Trasher29** [comment]
Ok, thanks for your feedback!
