### ISSUE TITLE
[BUG] Phone crashing when moving app to microSD

### ISSUE THREAD

**Issue by igglasty** [ananjaser1211/hadesRom_Reports#105]
**Describe the bug**
Phone crashes or displays black screen after 2 or more operations. Operation - moving app to microSD.

**To Reproduce**
1. Click on notification saying that new microSD is installeed
2. Click on app that you want to move
3. Click ok
4. Sometimes it happens instanly, sometimes we can see progress in moving app

**Expected behavior**
I expect the phone crash that can reload itself, as if its now i have to force restart it.

**Smartphone (please complete the following information):**
Regular european exynos N950F Galaxy Note 8

**Comment by ananjaser1211** [comment]
I have moved 4 apps back to back on my device through that option. So far so good. Did take some time for big apps but seems to be fine.

I'm gonna need a log the captures the process start to finish (both log_v and log_error)

![Screenshot_20210920-102729_Device care.jpg](https://user-images.githubusercontent.com/25624482/133963637-6bd8b932-41eb-4ee9-8ed8-68cd12feb00f.jpg)

![Screenshot_20210920-102415_Storage booster.jpg](https://user-images.githubusercontent.com/25624482/133963650-3b531969-9544-4637-8122-de99321137d5.jpg)
