### ISSUE TITLE
[Feature] outdoor mode in bixby button 

### ISSUE THREAD

**Issue by abadi718** [ananjaser1211/hadesRom_Reports#107]
**Describe the feature**
Add outdoor mode to the list of bixby button in Aroma, it will be more useful because if you are out side home you can't see screen to navigate settings>display>outdoor mode. 
I hope this is clear for you,
Thanks

**Expected behavior**
Pressing on bixby button will toggle outdoor mode on or off.

**Comment by ananjaser1211** [comment]
there is no native feature / key layout combo that enables outdoor mode, and i dont know how to implement such. if someone else can they can update this issue.

regardless, outdoor mode auto enables once in direct sunlight and autobrightness is enabled, atleast it does that on my Note 8 and S9+
