### ISSUE TITLE
[BUG] RAM Full when multitasking

### ISSUE THREAD

**Issue by Ben2557** [ananjaser1211/hadesRom_Reports#108]
I'm getting slow downs when multitasking. The RAM gets full which causes a standby drain issue and some lags (not freezes like V1) on the UI when using the phone.

This usually happen without closing recent apps and listening to podcasts in the background while utilizing an another app.

For the numbers, I got today 3 to 3.5%/an hour of standby drain with a good cellular network (using single SIM card) with a CPU deep sleep of 60% most of the time, no background tasks when screen is off.

Smartphone :
 - Device : Galaxy S8+
 - Model : G955FD

I'm (again) suspecting LMK values. They changed since V1 and it seems they're too low, letting RAM management too light.

However, when clearing RAM manually for testing purpose, I get 0.7%/an hour drain.

**Comment by ananjaser1211** [comment]
in V2 we switched to 4GB LMK setup from my S7 Rom, they are not the best there either in all honesty, if LMK worked well in V1 i could revert the change.

**Comment by Ben2557** [comment]
After testing with LMK fix I used on V1, battery drain has not been fixed. I have only 60% of deep sleep on the CPU with a drain of 3 to 5%/hour screen off.

For now, I don't know at all where comes the issue. Maybe it's only me but I never had that on V1 with the same setup.

I'll let you know as soon as possible if I find something but you may shouldn't taking into account previous LMK values because it seems I have more lags with that compared to your own values...and the problem remain the same.

**Comment by Ben2557** [comment]
[UPDATE 1]

The drain was an issue due to a bug between the Bluetooth connection between my PC and the phone.
**So this is fixed now,** I can now confirm there's no battery drain in V2.

I'll make a last UPDATE later this week about LMK values, which I will test in order to find a balance between lags and full RAM.

**Comment by ananjaser1211** [comment]
@Ben2557 Alright thank you

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
