### ISSUE TITLE
List of issues getting in Hades V2

### ISSUE THREAD

**Issue by Bravolol31** [ananjaser1211/hadesRom_Reports#112]
Some List of issues im getting in Hades v2 :

1. Audio quality from the speaker is not good, audio somehow not clear tho and not loud like pie.
2. Green line on the status bar while plugging charging and in AOD.
3. Idk if im getting this issue or not, but while in Zoom meeting, i cant minimise it, was working fine before on every rom.
4. Camera not saving pictures while zooming to 8 or 10x
5. Some banking apps not working even after Magisk hide too...But not care
6. Ram management not good with hades kernel, improved after flashing RZ kernel tho.
Overall the rom is a beast except these things, Big thanks to Corsicanu and other devs.

 - Device: [Galaxy S8]
 - Model: [G950F]

**Comment by ananjaser1211** [comment]
1. this is the new audio tune by samsung, it cant be changed in Q.
2. mentioned in #9 
3. this depends on your meeting type, most meetings dont support background play (same behavior on my S9+ and iPhone X with university meetings) to be sure this isnt a ROM bug i tested stock pie rom with the same zoom meeting and it closed
4. mentioned in #101 
5. This depends on your bank and how strict they are with rooting, nothing can be done
6. mentioned in #108 i noticed (on S8 mainly) that certain apps flood the RAM, right now there does not seem to be much that can be done aside from regular device maintenance > clear apps, a common app that seems to have caused ram issues on S8s is tiktok v21 so try to close it if you have the app when you are done with it

for other issues please open a separate bug report with logs as it makes visibility easier. Thanks

**Comment by workonfire** [comment]
Regarding to the 4th problem, sometimes the camera hangs and shows an error.

_Server error. Restart the app._

![Screenshot_20211014-135247_Camera.jpg](https://user-images.githubusercontent.com/34654573/137327531-93808e2a-59bb-4edb-b27b-dded19f0ddc5.jpg)
