### ISSUE TITLE
Mic when I'm loud speaker

### ISSUE THREAD

**Issue by Eazbir** [ananjaser1211/hadesRom_Reports#113]
- On a call, when in loud speaker, the person on the other side struggle to hear me out. 

- The panorama mode does not finalise the picture and it get stuck after confirming. 

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - Model: G950F

**Comment by ananjaser1211** [comment]
panorama / wide selfie and burst shot will be fixed in V2.1
i could not recreate the loud speaker issue so far, there are some changes in the audio system in 2.1 so the issue might just solve itself. will see

**Comment by nandxor** [comment]
> * On a call, when in loud speaker, the person on the other side struggle to hear me out.
> 
>     * The panorama mode does not finalise the picture and it get stuck after confirming.
> 
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: Galaxy S8
> 
>     * Model: G950F

I am having the same issues (Microphone on loudspeaker and panorama) on my G950F

**Comment by ananjaser1211** [comment]
Audio system has been re-tuned in V3.0, please re-test and re-open if needed
