### ISSUE TITLE
[Feature] adjust mic gain manually

### ISSUE THREAD

**Issue by AMasrar** [ananjaser1211/hadesRom_Reports#115]
**Describe the feature**
The mic gain adjustment in the V2 has made it difficult for others to hear me while using headphones. Is it possible to change the mic gain for headphones manually? If so, a small how to will be very appreciated and if you can include the previous values found in V1 will be perfect. Thanks.

**Comment by ananjaser1211** [comment]
Headphones has been boosted in V3.0, please try and re-open if needed
