### ISSUE TITLE
[BUG] LockStar App from Samsung GoodLock not working anymore

### ISSUE THREAD

**Issue by Ben2557** [ananjaser1211/hadesRom_Reports#116]
**Describe the bug**
When changing some settings from the LockStar app, it doesn't apply to the lock screen.
I can confirm this is an issue from V2, V1 doesn't have any problem.

**To Reproduce**
1. Go to 'GoodLock app' **from the Galaxy Store**
2. Click on 'LockStar'
3. Apply some settings such as wallpaper, clock or anything else...
4. Go back to lock screen of your phone.

**Expected behavior**
Changes made using LockStar should be taken into account.

**Smartphone :**
 - Device: Galaxy S8+
 - Model: SM-G955FD

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
