### ISSUE TITLE
[BUG] Dex mode slowdown

### ISSUE THREAD

**Issue by Tristan20033** [ananjaser1211/hadesRom_Reports#117]
When using dex mode. When the phone's screen lights up, Dex starts slowly work. And when you blank your phone screen, it works fine.

It's bothersome because often the phone screen lights up when someone calls, or if you want to talk to someone, for example on a discord on webcams, simply backlighting the phone screen slows down the dex mode and the phone itself, after turning off the screen everything is fine.

Samsung note 8 (sm-n950f)

**Comment by ananjaser1211** [comment]
Issue #72 . no fix for now
