### ISSUE TITLE
Keeps deleting some app files

### ISSUE THREAD

**Issue by jimmyntak** [ananjaser1211/hadesRom_Reports#118]
So Every 2-3 days downloaded songs in Spotify and downloaded files in Google Drive are getting deleted. 

European Enxynos Note 8

**Comment by jimmyntak** [comment]
* fresh installed ROM. No other mods etc

**Comment by ananjaser1211** [comment]
This is samsung device care (the cleaner) it clears their android/data folders as those are considered cache, but these apps download content there for some reason.

go to settings > device care > storage > storage booster > Disable Auto Delete unnecessary data

i dont remember how you exclude apps from that cleaner but you can look it up as this is a normal feature in oneui
