### ISSUE TITLE
[BUG] Call Recorder 

### ISSUE THREAD

**Issue by celth** [ananjaser1211/hadesRom_Reports#12]
**Describe the bug**
Doesn't record calls

**To Reproduce**
When I make a call doesn't  appear the option to record

**Expected behavior**
I have already flashed twice selecting call recorder the HR Q V1.0 even changing the region but doesn't  work.

**Screenshots**
![Screenshot_20201227-222851_Call](https://user-images.githubusercontent.com/76673445/103187620-02d77880-4893-11eb-8746-c87332a5cd3a.jpg)

**Smartphone (please complete the following information):**
 - Device: [Note 8
 - Model: [ N950F]

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by corsicanu** [comment]
I have call recorder and it works on both Note8 and S8. Can you look under 3dots menu on top right corner?

**Comment by corsicanu** [comment]
Will close this issue as it's working for me and other 5 people that checked.
