### ISSUE TITLE
[BUG] Drivedroid Hosting

### ISSUE THREAD

**Issue by K11DD3ATH** [ananjaser1211/hadesRom_Reports#120]
Drivedroid doesn't find a hosting device no matter which kernel mode is selected. 
Device : N950F

![Screenshot_20211110-073542_DriveDroid](https://user-images.githubusercontent.com/22484721/141164545-dab0a2dc-c3c6-4169-9d0d-e0e7b6d17f7b.jpg)

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
