### ISSUE TITLE
[BUG] Lift to Wake not work

### ISSUE THREAD

**Issue by Stefan3324** [ananjaser1211/hadesRom_Reports#125]
Lift to wake dont work,on version 2.0 is work normal,but on 3.0 not work.

Phone:S8 Plus![20220212_005915.jpg](https://user-images.githubusercontent.com/96664034/153686505-4077eccb-ba44-42f4-8a9f-73323c9ea7a3.jpg)

**Comment by Snowers96** [comment]
On S8 this work well

**Comment by ananjaser1211** [comment]
Works as expected on my Note 8. try to re-enable it
