### ISSUE TITLE
[BUG] Super Slow Motion is missing on v3.0

### ISSUE THREAD

**Issue by prince-879804** [ananjaser1211/hadesRom_Reports#128]
Why is no super slow motion option on the camera in the HadesQ rom v3.0 for the galaxy s8 exynos?

**Expected behavior**
i expected a respon.

**Screenshots**
![Screenshot_20220222-081521_Camera](https://user-images.githubusercontent.com/100174391/155045596-e9225f3d-e9c2-4b4e-a7bf-a98ef4fffe79.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - Model: SM-G950F 

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by ananjaser1211** [comment]
#2
