### ISSUE TITLE
[BUG] call in bluetooth (Blowing) (SmartWatch, Car)

### ISSUE THREAD

**Issue by Arterter** [ananjaser1211/hadesRom_Reports#13]
**Describe the bug**
Bluetooth call sound blowing (Car and Smartwatch)

**To Reproduce**
Make a call in bluetooth 

**Screenshots**
![Screenshot_20201228-154346_Settings](https://user-images.githubusercontent.com/36677539/103227147-9b1e3d80-4925-11eb-9707-863dd45af97d.jpg)
![Screenshot_20201228-154348_Settings](https://user-images.githubusercontent.com/36677539/103227153-9d809780-4925-11eb-8d6e-1e92efd2ef23.jpg)
![Screenshot_20201228-154351_Settings](https://user-images.githubusercontent.com/36677539/103227158-9f4a5b00-4925-11eb-8442-03c5b591842f.jpg)
![Screenshot_20201228-154353_Settings](https://user-images.githubusercontent.com/36677539/103227162-a1141e80-4925-11eb-9af8-ca190286521d.jpg)
![Screenshot_20201228-154356_Settings](https://user-images.githubusercontent.com/36677539/103227169-a2dde200-4925-11eb-9585-20be4c042397.jpg)
![Screenshot_20201228-154358_Settings](https://user-images.githubusercontent.com/36677539/103227177-a7a29600-4925-11eb-8744-2ccde4bb6c03.jpg)

**Smartphone (please complete the following information):**
 - Device: [Galaxy S8]
 - Model: [G950F]

**Additional context**
TRY THE SOLUTION IN THE SCREENSHOT SEQUENCE, i think it should resolve

**Comment by Townie-au** [comment]
That work around doesn't work unfortunately. 
I tried it while the device is connected and without.

**Comment by Townie-au** [comment]
When I make a call via Bluetooth. Both our voices sound like a robot. Only when making a call and only through Bluetooth. Is this what you guys are getting?.

**Comment by ananjaser1211** [comment]
Sounds like you are blowing at the mic or so

**Comment by Townie-au** [comment]
> Sounds like you are blowing at the mic or so

Ughh no. I'm talking.

**Comment by Arterter** [comment]
> > Sounds like you are blowing at the mic or so
> 
> Ughh no. I'm talking.

Try to turn off ringtone sync and try to make a call, dont turn on again

**Comment by Townie-au** [comment]
> > > Sounds like you are blowing at the mic or so
> > 
> > 
> > Ughh no. I'm talking.
> 
> Try to turn off ringtone sync and try to make a call, dont turn on again

Yep. That worked. Thanks mate.

**Comment by Arterter** [comment]
> > > > Sounds like you are blowing at the mic or so
> > > 
> > > 
> > > Ughh no. I'm talking.
> > 
> > 
> > Try to turn off ringtone sync and try to make a call, dont turn on again
> 
> Yep. That worked. Thanks mate.

maybe i should update the image to the people dont turn on again @corsicanu

**Comment by Townie-au** [comment]
> > > > > Sounds like you are blowing at the mic or so
> > > > 
> > > > 
> > > > Ughh no. I'm talking.
> > > 
> > > 
> > > Try to turn off ringtone sync and try to make a call, dont turn on again
> > 
> > 
> > Yep. That worked. Thanks mate.
> 
> maybe i should update the image to the people dont turn on again @corsicanu

I was actually able to turn it on again after making a call while it was off with no issue. Go figure.

**Comment by Niels7801** [comment]
have the same issue, workaround not working for me, when I switch to phone speaker and back to bt headset during a call is working.Tried the workaround with leaving the switch off or turning back on both cases don't work.

**Comment by Bogdans29** [comment]
> > Sounds like you are blowing at the mic or so
> 
> Ughh no. I'm talking. 

Try to download (if you using magisk)
"Bluetooth Libary patcher" module and install it reboot. .

**Comment by ananjaser1211** [comment]
@Bogdans29 The module patch is already applied in the rom. wait for V2 for a fix to this bug
