### ISSUE TITLE
Motion photo missing

### ISSUE THREAD

**Issue by szymon420699** [ananjaser1211/hadesRom_Reports#131]
Ik motion photos is broken but is there a way to just turn it on even tho its broken?

**Comment by ananjaser1211** [comment]
in system/cameradata/camera-feature.xml

remove the line `<local name="SUPPORT_MOTION_PHOTO" value="false" />`

you will get the option for motion photo, you will not be able to take any photos however.

**Comment by szymon420699** [comment]
So i removed the line but the option is not there should i just leave it because i want to take motion photos on my phone even tho its broken .

I even tried changing the statement to true, removing it like you told me to and restarted the phone. But that didnt do anything

I made two different copies of the file. I named the orginal 
camera-feature(orignal).xml
and the other copy to 
**camera-feature(orignal).xml**
It doesn't show up the option or anything.



Not sure if thats the problem that the motion photos option is showing up but when i look at the right there are some letters not sure what it is but they are different.
It might be the permissions im not fully sure.

![Screenshot_20220526-232108_Root Browser.png](https://user-images.githubusercontent.com/83908636/170589734-f4ed391e-8f10-4046-ad47-903a23c8176d.png)

**Comment by ananjaser1211** [comment]
either true or the line being removed, you will see the motion photo logo, no you cant take motion photos at all. it will just show camera server error, or wont save the photo and wont create a file.

**Comment by ananjaser1211** [comment]
looking at the screen shot you posted the file permissions are wrong, change them to 0755. and clear camera data in settings.

**Comment by szymon420699** [comment]
Changed permmisions and the option is not there at all did the instructions u told me to do but the option doesnt show up in the setting or in the camera removed the stamenet as well but its not there either and i removed the file data instructions before i did this
