### ISSUE TITLE
[BUG] Only one rear camera is working

### ISSUE THREAD

**Issue by AustinMuoz** [ananjaser1211/hadesRom_Reports#133]
**Describe the bug**
The galaxy note 8 has two cameras and only one works.

**To Reproduce**
1. Go to 'Camera app'
2. Fingertip cover of only one of the two rear cameras.
3. Click on "zoom 2.0x"  (🌲) 
4. Now, Click on "zoom 1.0x"  (🌲🌲) - Cover the following rear camera with your finger.
5. Click on "zoom 2.0x"  (🌲)

**Expected behavior**
You will notice that only one of the two cameras is functional, leaving one of them unusable. When zoomed in x2, the system switches cameras.

**Smartphone (please complete the following information):**
 - Device: [Galaxy Note 8]
 - Model: [G950F]

**Comment by ananjaser1211** [comment]
Refer to https://github.com/ananjaser1211/hadesRom_Reports/issues/29#issuecomment-753479135

Telephoto activates under 2.4x and higher in well lit room
