### ISSUE TITLE
[BUG] MHL didnt work for Samsung Dex

### ISSUE THREAD

**Issue by twinnybloggers** [ananjaser1211/hadesRom_Reports#135]
Dear Dev, i have issue when My MHL adapters (Type C to VGA) plug in, it just said "usb connector connected". No samsung dex show up . 

Im using samsung dex 4 month , but after 1 month trying to plug in vga adapters  (Type C to VGA)  it just show "usb connector connected" and no Sign "HDMI input".

Can u help me what happed with my this issue? 

Editted: im using HadesRom Q v3 and try to install HadesRom Pie v12 its same problems

Best regards

**Comment by ananjaser1211** [comment]
Just got around to checking issues, I dont own MHL so i cant directly test it, but if MHL is not working on Pie then it could be faulty MHL cable
