### ISSUE TITLE
How to delete handsRom and return to default rom?

### ISSUE THREAD

**Issue by whrgo** [ananjaser1211/hadesRom_Reports#136]
I recently installed handsRom and suffered inconvenience because it does not support various things I do.

How do I delete handsRom?

**Comment by ananjaser1211** [comment]
@whrgo Download stock firmware from websites such as samfw (just type in your phone's model number)

Follow the guide on that website or simply download latest version of Odin. Unpack the zip you downloaded (extract the 5 files) and drag the files you downloaded to the sections in Odin

AP CP CSC And BL. For CSC drag the file with the name CSC* And not HOME_CSC to perform full wipe

Put your device in download Mode. Plenty of guides online. And press start in Odin. HandsRom will be removed

**Comment by whrgo** [comment]
> 

Oh my thanks
