### ISSUE TITLE
[BUG] LED colors are inaccurate.

### ISSUE THREAD

**Issue by Hidden-Help** [ananjaser1211/hadesRom_Reports#14]
**Describe the bug**

LED indicator colors are mismatched. for example if you change the LED color in any app like telegram to YELLOW for example, it will be 90% red while in the older version in stock it was yellow and you could see the color difference in LED.

**To Reproduce**

1. Go to LED indicator in any app like telegram/whatsapp/messenger etc under settings, Notifications and sounds, Private chats, LED color.
2. Change it to any color apart of RED, GREEN and BLUE.
3. Tell anyone to send you a private message and you'll see the LED color is mismatched.

**Expected behavior**

Color of LED to be very very close to the actual color picked in settings. on pie Colors like purple , white , yellow and others looked really close to the actualy colors.

**Screenshots**
Don't have a different Phone right now, sorry.

**Smartphone:**
 - Device: [Galaxy note 8].
 - Model: [N950FD]

**Additional Info**

Sometimes the LED will show the color you picked in settings for few seconds then turn back to blue and ignore the picked color. but i'm not sure if it's a bug caused by the ROM so Please forgive me if that's not a bug.

Merry Christmas.

**Comment by corsicanu** [comment]
@Hidden-Help We're testing now some cases on S9+ to see if it's not actually Samsung related. So far we discovered orange in settings makes pink led. White also goes to a pinkish color. 
So this might actually be on Samsung since on full stock rom S9+ led behaves weird too... 
We'll test further and report here.

**Comment by ananjaser1211** [comment]
This seems to be something with oneui 2 itself, i tried various colors, basic colors like Red, Green, Blue seem to be fine. mixed colors behave weird on both phones (S9+ running stock, N8 running hades Q)

color also seems to change based on ambient light, and both the S9 and N8 cant produce consistent color, each pulse is slightly different.

so ill have to mark this as a non-rom related bug

Left ( Note 8 ) Right (S9+) . Telegram set to White. edit : forgot to mention this, IRL they are purple/pink~ish

![image](https://user-images.githubusercontent.com/25624482/103237455-85485280-48fc-11eb-9562-8cacac24ddb0.png)

**Comment by corsicanu** [comment]
Closing this as it's not a rom bug, rather samsung/oneui related. Either way it's nothing we can fix from our side.
