### ISSUE TITLE
[BUG] Auto-reverse text color is not working in dark mode

### ISSUE THREAD

**Issue by Hidden-Help** [ananjaser1211/hadesRom_Reports#15]
**Describe the bug**

Auto-reverse text color is not work in dark mode. changing the option doesn't change anything, the colors stay the same.
it works when dark mode is OFF only.

**To Reproduce**
1. Turn on dark mode
2. Go to settings, lock screen , notifications (make sure view style is "details").
3. now try changing Auto-reverse text color option.
4. See error, nothing is changing

**Expected behavior**
Auto reverse colors to work during Dark mode and change the colors of the notification text

**Screenshots**
![Dark mode ON and same colors in reverse color option anabled or disabled](https://user-images.githubusercontent.com/76661080/103237622-cec28d00-4950-11eb-85a5-e5650de38ae7.png)
![Dark mode OFF, see the colors are changed](https://user-images.githubusercontent.com/76661080/103237633-d41fd780-4950-11eb-9d4d-00c38aeada4d.png)

**Smartphone (please complete the following information):**
 - Device: [Galaxy note 8]
 - Model: [N950F]

**Additional context**
with love

**Comment by ananjaser1211** [comment]
All good in darkmode on and off. i have tested multiple wallpapers on both my galaxy S9 and my note 8. both reacted the same.

maybe try and mess with settings > disp > darkmode settings > apply to wallpaper. but i dont think it is related to lock screen.

this seems to be just normal behavior in 2.5, unless the image is white enough, it wont flip the text.


https://user-images.githubusercontent.com/25624482/103265792-41d4ff00-4963-11eb-8694-91e37d4894cf.MOV
