### ISSUE TITLE
[BUG] quick share

### ISSUE THREAD

**Issue by faisal3338** [ananjaser1211/hadesRom_Reports#16]
**Describe the bug**
Quick share is not working. When I try to send or receive a files by quick share, the WiFi immediately goes off and the operation failed.

**Smartphone (please complete the following information):**
 - Device: [Galaxy N8]
 - Model: [N950F]

https://user-images.githubusercontent.com/13709806/103238745-a93b8080-495c-11eb-918b-9a3c23c142f5.mp4

**Logcat:**
[Log_2020-12-28_22-16-44.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/5748551/Log_2020-12-28_22-16-44.txt)

**Comment by ananjaser1211** [comment]
This feature is unsupported on our WiFi hardware (Kernel Driver / blobs) and will probably never be fixed.

use Nearby Sharing instead

**Comment by Snowers96** [comment]
> This feature is unsupported on our WiFi hardware (Kernel Driver / blobs) and will probably never be fixed.
> 
> use Nearby Sharing instead

Hi! Could you hide this setting in a later release?

**Comment by ananjaser1211** [comment]
> > This feature is unsupported on our WiFi hardware (Kernel Driver / blobs) and will probably never be fixed.
> > use Nearby Sharing instead
> 
> Hi! Could you hide this setting in a later release?

Thats the plan

**Comment by lucf15** [comment]
Quick share works on Note8 (SM-N950F) to me though.

https://user-images.githubusercontent.com/66513551/103466167-d1ebbd80-4d42-11eb-99da-294469798012.mp4

**Comment by ananjaser1211** [comment]
it can transmit sometimes, and even fewer times it can receive  , but will 90% of the time fail and turn off wifi, especially when it is receiving. 

hence why its going to be removed, until i have time to study the kernel driver and see what makes it tick. there are some changes in the wifi driver in Q that allow the wifi to go into modes without turning off.

**Comment by ananjaser1211** [comment]
Qucikshare has been dropped from the ROM due to unsupported drivers/blobs.
