### ISSUE TITLE
[BUG] weird noise in calls  wen using Bluetooth headphones  

### ISSUE THREAD

**Issue by ramzyk40** [ananjaser1211/hadesRom_Reports#18]
**Describe the bug** 
Wen calling in phone (not messnger and other...) a weird noise come and i can't hear anything 

**To Reproduce**
1. Just call some one using Bluetooth headphones 

**Smartphone 
 - Device: [Galaxy S8]
 - Model: [G950F]
  @#`
[Log_2020-12-30_14-55-31.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/5754427/Log_2020-12-30_14-55-31.txt)
`

**Comment by ananjaser1211** [comment]
Duplicate #13 follow the workaround there

**Comment by ramzyk40** [comment]
Well i try it and noise still there
