### ISSUE TITLE
[BUG] Voice Repeating On Phone Calls. 

### ISSUE THREAD

**Issue by Mrdaniyal** [ananjaser1211/hadesRom_Reports#19]
**Voice Repeating On Phone Calls**
Describe your issue here. 
Whenever i Recieve Call From Someone They Complain that there voice is repeating to them. 
When
**To Reproduce**
1. 'Call Someone'
2. 'Set Call Volume On Full' 
3. See error

**Expected behavior**
The Person I call should not hear there voice repeating to them. 

**Smartphone :**
 - Device: [Galaxy Note 8]
 - Model: [Sm-n950FD]

**Comment by ananjaser1211** [comment]
Are you using dualspeaker mod in aroma

**Comment by Mrdaniyal** [comment]
> Are you using dualspeaker mod in aroma

No I'm Not Using Dual Speaker.

**Comment by corsicanu** [comment]
Possible duplicate of #6 , earpiece volume higher than normal. As a workaround don't switch to maximum volume, use 1-2 steps lower.
