### ISSUE TITLE
[Feature] lockscreen mode rotation

### ISSUE THREAD

**Issue by bloodyErik** [ananjaser1211/hadesRom_Reports#21]
Landscape mode of lock screen in "auto rotate" is missing.
![Screenshot_20201231-120819_Chrome.jpg](https://user-images.githubusercontent.com/76806934/103401171-52eb5f00-4b61-11eb-93cd-0e44e6e3b483.jpg)
 - Device: [Galaxy S8 Plus]
 - Model: [G955FD]
Best regards.

**Comment by ananjaser1211** [comment]
This is no longer an option on stock oneui. here is a screenshot from my S9+ running stock oneui 2.5

![image](https://user-images.githubusercontent.com/25624482/103401244-862dee00-4b61-11eb-86cc-ac67328be29c.png)

**Comment by bloodyErik** [comment]
> This is no longer an option on stock oneui. here is a screenshot from my S9+ running stock oneui 2.5
> 
> ![image](https://user-images.githubusercontent.com/25624482/103401244-862dee00-4b61-11eb-86cc-ac67328be29c.png)
> 

ok, thank you
