### ISSUE TITLE
[BUG] QS panel

### ISSUE THREAD

**Issue by bloodyErik** [ananjaser1211/hadesRom_Reports#22]
I don't think it is that causeful thing to fix it but just in case, when you pull the quick settings panel down once, pulling it down continuously, it pulls down a little bit laggy. It is more noticeable when dark mode is not on. Everytime when I pull it down once and continue to pull it down(i mean when I don't open it fully) I feel that it pulls down not smoothly. Unfortunately, I couldn't catch that on screen recording. Sorry, if this report was not reasonable.
 - Device: [Galaxy S8 Plus]
 - Model: [G955FD]
 Best regards.

**Comment by ananjaser1211** [comment]
report is fine, the "bug" is just the nature of unofficial higher android ports, you are not going to get 60 FPS and smooth animations everywhere in the system. there will be some drops sometimes. but imo there is no feasible way to get rid of them

**Comment by bloodyErik** [comment]
ok, got it
