### ISSUE TITLE
[BUG] Screen transition effect

### ISSUE THREAD

**Issue by bloodyErik** [ananjaser1211/hadesRom_Reports#23]
Transition effect does not work when unlocking with fingerprint.
 - Device: [Galaxy S8 Plus]
 - Model: [G955FD]

**Comment by bloodyErik** [comment]
usually

**Comment by ananjaser1211** [comment]
after long testing on both the N8 with hadesQ and S9+ With stock rom, they are about the same, both miss `some` transition effects and sound randomly. it seems to be oneui2 related shenanigans. 

nothing i can do ROM Wise to eliminate that as its a samsung bug
