### ISSUE TITLE
[BUG] USB Mouse support

### ISSUE THREAD

**Issue by adil192** [ananjaser1211/hadesRom_Reports#25]
**Describe the bug**
Phone doesn't respond to a wired mouse or keyboard on v1.0

**To Reproduce**
1. Connect USB mouse/keyboard to a Samsung usb adapter
2. Nothing happens - phone doesn't respond to keys or mouse strokes

**Expected behavior**
Phone shows a notification for "Physical keyboard settings" and allows you to type/click.

**Screenshots**
N/a

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - Model: G950F
 - CSC: BTU (Unlocked UK)
 - Rooted with Magisk 21.1, only using Adaway and Magisk Hide

**Additional context**

> ---- 31 Dec 2020 16:00:58 ----
> 
> 12-31 16:01:00.526  4466  4577 E Watchdog: !@Sync 164 [2020-12-31 16:01:00.526] FD count : 606, wdog_way : softdog
> 
> 12-31 16:01:00.527  4466  4577 E Watchdog_N: !@Failed to ioctl to /dev/watchdog1 // errno : 25
> 
> 12-31 16:01:01.012  9822  9822 E MdxKitService: (DeviceConnectionServiceViewModelImpl) terminate()-[td:main] killProcess, pid: 9822
> 
> ---- 31 Dec 2020 16:01:06 ----
>

**Comment by accordion123** [comment]
working. i test with bluetooth mouse. G955F.

**Comment by corsicanu** [comment]
Log is not useful, try with a log app from playstore while connecting them.
Aside from that my Lenovo 400 wireless mouse with original type C otg from phone box works on my Note8. 
What device you are trying to connect? Maybe samsung kernel lacks drivers of your attached device.

**Comment by ananjaser1211** [comment]
cheapo mouse/keyboard wireless combo (on single reviver usb) is working on my note8

**Comment by adil192** [comment]
The keyboard I've tried is the Cherry JK-0300GB and the mouse is the CoolerMaster MM830. I'm using the original OTG from my phone box which works on another S8. Also tried with a usb flash drive which doesn't work. Maybe the port is damaged?
Also nothing really showed up in the log (the one above is when I plug in and unplug a mouse).

**Comment by corsicanu** [comment]
@adil192 Most likely hw fault. Are the keyboard and mouse working on the s8 on hades Q?

**Comment by adil192** [comment]
I don't have Q on the other S8. I'll test it later if I have time.

**Comment by adil192** [comment]
The other S8 worked fine. Must be a hardware issue.
