### ISSUE TITLE
[BUG] Major delay in picture taken from camera showing in gallery

### ISSUE THREAD

**Issue by Townie-au** [ananjaser1211/hadesRom_Reports#26]
**Describe the bug**
Major delay picture taken from camera showing in gallery 

**To Reproduce**
1. Go to 'Camera'
2. Click on 'Take Photo Button'
3. Look down to circle where picture you just took shows up
5. Click on circle not in gallery

**Expected behavior**
Newly taken picture should show in circle and pressing the circle should show the picture in gallery

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: [Note 8 Exynos]
 - Model: [SM-N950F]

**Additional context**
Logs available on request I can send by personal message in case contains personal info

##Solution## Decompiled rom with ApkSwapper, replaced camera app with latest android 10 Samsung camera app v10.5.03.14 from APKMirror, recompiled and then did a full wipe, including data and internal storage and re-flashed the rom. Fixed :)

**Comment by ananjaser1211** [comment]
i tried 10.5.02.11 apk but it refuses to open the app, is that the exact version you used ?

**Comment by Townie-au** [comment]
> i tried 10.5.02.11 apk but it refuses to open the app, is that the exact version you used ?

Crap, Sorry. No it was this one.

https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-camera/samsung-camera-10-5-03-14-release/samsung-camera-10-5-03-14-android-apk-download/download/

**Comment by SypeR54** [comment]
@Townie-au Even you try to use stock same Camera apk, it wont work. Because we have modded Camera apk to work as is. Some unsupported features (such as HDR10+ recording etc) disabled hard.

**Comment by Townie-au** [comment]
I'm using it. It works great.On 3 Jan 2021 7:11 am, Yasin SypeR <notifications@github.com> wrote:
@Townie-au Even you try to use stock same Camera apk, it wont work. Because we have modded Camera apk to work as is. Some unsupported features (such as HDR10+ recording etc) disabled hard.

**Comment by ananjaser1211** [comment]
@Townie-au 

So, i tried every camera version that is 10.5+ on apk mirror, none of them worked.

i took the apk apart, this is a camera core v2 application, it will never run on our phones it does not have a single corev1 code. you did not replace the camera apk, and whatever fix you saw was a placebo.

you can tell by going to the video settings, if you have UHD and QHD 60 FPS options, you are still using the camera apk that was shipped in this rom. 

![image](https://user-images.githubusercontent.com/25624482/103687477-c64e0000-4fa9-11eb-895f-fd09968a8b9e.png)
