### ISSUE TITLE
[BUG] Microsoft YourPhone app can't be found or opened even though it is installed

### ISSUE THREAD

**Issue by rajitsingh** [ananjaser1211/hadesRom_Reports#27]
**Describe the bug**
Playstore says that the Microsoft YourPhone app is already installed on the phone, but the app can't be found on the system and can't be launched from it's page in the PlayStore (there is only an Uninstall option).

**To Reproduce**

1. Go the app drawer - the YourPhone app is nowhere to be found
2. Go to PlayStore and search for Microsoft YourPhone - it shows that the app is already installed
3. The app cannot be launched, just installed

**Expected behavior**
There should be a launcher for YourPhone in the app drawer and it should also be able to be launched from the PlayStore.

**Screenshots**
![Screenshot_20210101-211752_Google Play Store](https://user-images.githubusercontent.com/1999031/103442039-8967cd80-4c78-11eb-9311-27f176369ca6.jpg)

**Smartphone (please complete the following information):**

Device: Galaxy S8+ 955FD

**Additional context**
I never installed the app. It was supposedly pre installed in the ROM.

**Comment by corsicanu** [comment]
Settings - Advanced features - Link to windows
Also give a read to:
https://www.samsung.com/uk/support/mobile-devices/what-is-link-to-windows/

Closing it as it's not an issue.
