### ISSUE TITLE
[BUG] Music player goes to static after some time

### ISSUE THREAD

**Issue by Xenos7** [ananjaser1211/hadesRom_Reports#34]
**Describe the bug**
This happens while playing media on Samsung music, Phonograph, Spotify, don't know about YouTube tho (Edit: yeah, YouTube too).
I listen to music with wired 3.5mm earphones connected, for about 15-30 minutes, then I pause it, lock the phone, and I DON'T disconnect earphones from the phone.
Thing is, after 10-15 minutes, I come back, and there is a chance that when I click play, a STRONG static sound will play in the earphones instead of music.

**To Reproduce**
Sometimes it happens, sometimes it doesn't, I don't know how exactly to replicate it. Last time this issue happened, I paused the song, prepared the terminal, executed logcat, pressed play, still static, and then Ctrl+C in terminal after I paused again.
So far that's the last time it happened, as I said, I took a log, but, the log is 10mb of pure madness.
So, forgive me for what I'm about to do.

**Expected behavior**
By clicking the play button, music should start playing.

**Screenshots**
No screenshots, it's sound.

**Smartphone:**
 - Device: [Galaxy N8]
 - Model: [N950FD]

**Additional context**
- Gathered logs by using "logcat -b all > export.log"

Link to log: Edited out

Edit: It happened again, so here is an error-only one.
[sound_static_error_only.log](https://drive.google.com/file/d/1-L1Rn3GjbTvOVNlsfO99ozqBfkbp8Ppc/view?usp=drivesdk) 
And another one using logcat without parameters.
[sound_static_logcat.log](https://drive.google.com/file/d/1-RylzO-OBlC05WxHSHtxME6XdvYPOGo9/view?usp=drivesdk)

**Comment by Mrdaniyal** [comment]
I've Same Issue. Music Don't Play by Button after some time

**Comment by accordion123** [comment]
same issue g955f

**Comment by Townie-au** [comment]
Have you checked to see if battery optimization is off on the app your using?

**Comment by Xenos7** [comment]
Guys, I tried with battery optimization off as well, but it still happens.
Besides, it never happened on Pie even without touching battery optimization settings.
It's fine tho, a

**Comment by Xenos7** [comment]
I tried it with battery optimization off
Same thing happens
A quick fix is to unplug earphones, and play media, then replug while it's playing, it gets fixed

**Comment by Xenos7** [comment]
Also who decided to put Close button next to comment button on github
Sry about closing and reopening by accident

**Comment by ananjaser1211** [comment]
Got it today. Feels similar to the bluetooth issue

Possibly the two are caused by the same thing. While this is hard to reproduce the BT one is not.

Let's see..bluetooth static is caused by different pcm device in the audio hal we are using

**Comment by Jazzhead35** [comment]
Try changing sample rates and bits in developer options. For example, my Bluetooth DAC works with 48kHz / 16bit. Any other combination on phone's bluetooth settings causes distortion and noise. But when i set my phone to 48/16, audio becomes normal and plays for hours without any problem.

**Comment by ananjaser1211** [comment]
This was related to sampling rate and sUHQ, should be resolved now.
