### ISSUE TITLE
[BUG]High battery consumption

### ISSUE THREAD

**Issue by ThomasXDA** [ananjaser1211/hadesRom_Reports#39]
- Device: [e.g. Galaxy Note8]
 - Model: [e.g. G950F]
**Screenshots**
![Screenshot_20210104-143614_Device care](https://user-images.githubusercontent.com/76965762/103563775-9ed83400-4ed2-11eb-887f-498050533e7d.jpg)
) when applicable
Its not normal.pls fix it

**Comment by corsicanu** [comment]
Duplicate of #28
