### ISSUE TITLE
[BUG]Warming up the phone

### ISSUE THREAD

**Issue by ThomasXDA** [ananjaser1211/hadesRom_Reports#40]
The phone gets very hot when talking or voice chat in the game. Help me bro:(
Cpu 56°

**Comment by ananjaser1211** [comment]
Your CPU is made to go upto 85C

I use zoom calls and chrome often. Heat is not abnormal. 59C cpu is not high.

It will run a bit warmer than pie due to the heavier oneui skin. But this is a take it or leave it situation. You can't have it all.

Closing this as its not an "issue"
