### ISSUE TITLE
Brightness problem in direct sunlight

### ISSUE THREAD

**Issue by mdsarfaraj76** [ananjaser1211/hadesRom_Reports#42]
https://user-images.githubusercontent.com/71928705/103619629-451c4c00-4f5c-11eb-9d5f-1818507aedf6.mp4

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - All models are affected

**Additional context**

**Comment by mdsarfaraj76** [comment]
Video size is vary big..So I can't upload here..
I post in the telegram group

**Comment by SoRadGaming** [comment]
Same Issue on my S8+ seems as Samsung adds a whitten filter when it detects direct sunlight and maxes brightness, and that's not being used on this rom rn.

**Comment by Snowers96** [comment]
Same issue S8

**Comment by Townie-au** [comment]
Same issue on note sm-n950f

**Comment by ananjaser1211** [comment]
indeed it is broken on Note 8 too. just tested it outside

**Comment by Townie-au** [comment]
I don't know if this is much use but I noticed if the phone is unlocked and you go in the sunlight the brightness responds normally but not when its locked it actually goes dimmer.

**Comment by Townie-au** [comment]
Hey guys. This isn't a rom issue.
Its because in android 10 they adopted adaptive brightness and apparently it doesn't work very well.
If you download lux from the playstore like I did the brightness will function properly.

**Comment by Matrix-sudo** [comment]
Which lux app fixed the issue for you?
