### ISSUE TITLE
[BUG] NFC is not working on card label as MIFARE Plus

### ISSUE THREAD

**Issue by Pavlon333** [ananjaser1211/hadesRom_Reports#43]
The phone is Samsung SM-G950F.
After upgrading to hadesRom Q stopped reading NFC cards from apps. Everything worked on DeluxeROM Pie .
Google Pay works fine.
NFC TagInfo defines the card label as MIFARE Plus.
![Screenshot_20210105-211837_NFC TagInfo_cr](https://user-images.githubusercontent.com/77025478/103697462-fbaa1c00-4fb0-11eb-919b-47d4856a42dd.jpg)

[logcat.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5772688/logcat.zip)

**Comment by ananjaser1211** [comment]
Please move this into #20 discussion. as thats where we discuss everything related to NFC.

working on it
