### ISSUE TITLE
[Feature] Add support for Camera Control from Samsung smartwatches.

### ISSUE THREAD

**Issue by SoRadGaming** [ananjaser1211/hadesRom_Reports#44]
Add support for camera control from Samsung smartwatches.

Image of feature
![image](https://user-images.githubusercontent.com/47128515/103741648-8e989400-504d-11eb-94ee-ff7effcbe869.png)

**Expected behaviour**
A video stream to watch and the ability to remote take photos.

Phone:
 - Device: [Galaxy S8+]
 - Model: [SM-G955F]
 - Device: [Galaxy Watch]
 - Model: [SM-R800]

Currently opening the app on the watch launches the camera app on the phone yet there is no viewfinder preview and nothing works, I was able to get an error message saying something about an HDMI display output not working in the camera app (went away too quick).

**Comment by SoRadGaming** [comment]
I was able to get a screenshot of the error (seems more like a bug and not feature request lol).
I launched the remote app on the watch, it auto opens the phone's camera and this message is displayed. (Nothing works on watch)
![Screenshot_20210106-183835_Camera](https://user-images.githubusercontent.com/47128515/103742174-81c87000-504e-11eb-89da-30c519d0f7d8.jpg)

**Comment by Minto107** [comment]
Catch a log man. Do you think it's enough to show a toast notification of an error?

**Comment by SoRadGaming** [comment]
> Catch a log man. Do you think it's enough to show a toast notification of an error?

Its a feature request, the original s8 never supported this feature nor the s9 or note 9.

**Comment by SoRadGaming** [comment]
Feature Works
