### ISSUE TITLE
[BUG]Google Voice "Hey Google" can't be used

### ISSUE THREAD

**Issue by shinryuken3000** [ananjaser1211/hadesRom_Reports#45]
**Describe the bug**
Google Voice "Hey Google" can't be enabled

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/77060184/103775787-218ef980-5061-11eb-915d-68ff66e3af27.png)

**Smartphone (please complete the following information):**
 - Device: Note 8 and S8

**Comment by fatihaslan0101** [comment]
My Note8 also works
![Screenshot_20210107-023925_Google](https://user-images.githubusercontent.com/76794839/103833401-fe307280-5091-11eb-91e9-33e4fc912a6f.jpg)

**Comment by Snowers96** [comment]
I have an S8 an can enable and use this option

**Comment by shinryuken3000** [comment]
Unluckily, both my S8 and Note8 devices can't activate it. Also tried to delete Google voice sample, registered again, didn't succeed

**Comment by ananjaser1211** [comment]
Make sure to install google app from aroma, and hi bixby / ok google hotword support has been resolved in V2
