### ISSUE TITLE
[BUG] TeamViewer Host can't be used

### ISSUE THREAD

**Issue by shinryuken3000** [ananjaser1211/hadesRom_Reports#46]
**Describe the bug**
When using Teamviewer (either computer or android smartphone) to connect to Host app (https://play.google.com/store/apps/details?id=com.teamviewer.host.market&hl=vi&gl=US) of Teamviewer, the screen loses, gets black in FHD+ screen resolution mode. Applying WQHD+ will fix but it will use a lot of battery.

**Screenshots**
![Screenshot (1665)](https://user-images.githubusercontent.com/77060184/103776432-053f8c80-5062-11eb-960b-af499ddbaaab.png)

**Smartphone (please complete the following information):**
 - Device: Note 8 and S8

**Comment by ananjaser1211** [comment]
On WQHD it does similar thing on my S9 until I reboot it while wqhd is set. Then it is fine. I will test on N8 later. 

Can someone else also test and confirm ?

**Comment by shinryuken3000** [comment]
Well I have both Note8 and S8. I only apply WQHD, no need to reboot, it's fixed but drain battery. Thanks if anyone can fix to use on FHD
