### ISSUE TITLE
[BUG] sound quality is bad ( not volume level )

### ISSUE THREAD

**Issue by mid95** [ananjaser1211/hadesRom_Reports#47]
**Describe the bug**
Sound quality is bad on the rom , i have an original earphones , i mean tha quality sound is not stereo like should be , i have no problem with volume level.

**Smartphone :**
 - Device: [e.g. Galaxy S8]
 - Model: [e.g. G950F]

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by Bogdans29** [comment]
Same on note 8

**Comment by ananjaser1211** [comment]
Headphone or speaker ?

Headphones feels the same compared to hades pie.
Speaker is different and has less bass and more gain. 

Speaker won't be changed as that is the new Q sound tuning. But headphones I felt it was fine. Play with sound alive and try some configs out. I don't see an issue here or one that is reported by many members

**Comment by corsicanu** [comment]
@ananjaser1211 or it can be fixed only on our side since we addressed the other volume related issues. Let's leave this open for after next version and see if it got fixed in process of fixing other bugs.
