### ISSUE TITLE
[BUG] Deep Sleeping Apps

### ISSUE THREAD

**Issue by faisal3338** [ananjaser1211/hadesRom_Reports#48]
**Describe the bug**
Deep sleeping apps doesn’t show my apps and I can’t add or delete apps. It says “no apps” when I try to add app to deep sleep.

**To Reproduce**
1. Go to ‘settings '
2. Click on 'device care'
3. Click on 'battery'
4. Click on 'app power management'
5. Click on 'deep sleeping apps'
6. Click on 'add apps'

**Screenshots**

![0E558FAB-DCC3-4177-AF5F-574642C665BF](https://user-images.githubusercontent.com/13709806/103907267-1fd13e80-5112-11eb-89ab-f3e2c4a3302f.jpeg)

**Smartphone (please complete the following information):**
 - Device: [Galaxy N8]
 - Model: [N950F]

**Comment by SypeR54** [comment]
@faisal3338 On Q, Device Care's methods are changed. You should spend some time (like around 2 days after you setup the phone) on the phone. Because its learning your usage style and then its suggest apps or automatically add apps in that list.

**Comment by Snowers96** [comment]
I dont have this problem. Galaxy S8

**Comment by ananjaser1211** [comment]
![Screenshot_20210109-033903_Device care.jpg](https://user-images.githubusercontent.com/25624482/104075435-3f5c8a00-522c-11eb-8290-111104f22dda.jpg)

Sleeping apps and deep sleeping apps will show up. It may take more time but generally speaking device manager takes few days to fully build up (and optimize)
