### ISSUE TITLE
[BUG] [N950N] [ATT] Hotspot issue on Q v1.0

### ISSUE THREAD

**Issue by adel-2** [ananjaser1211/hadesRom_Reports#49]
**Description**
Hotpot not working properly on N950N. It can be setup and on normally. Even devices can connect to it but no internet is delivered. "This page cannot be displayed"

This issue is only is affecting the Q v1.0 Rom not the previous Rom (v12)
I also noticed that install doesn't offer LUC csc anymore on the new Q v1,0 ROM so I kept my previous csc without selecting a new one.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Connections'
3. Scroll down to 'Mobile Hotspot and Tethering'
4. Turn On and Setup Hotspot

**Expected behavior**
After devices connects to hotspot it still cannot browse internet

**Smartphone (Install Steps):**
 - Device: [Galaxy N8]
 - Model: [G950N]
 - Sim: ATT
 - Clean Install
 - Kept previous csc (LUC), also tried KOO and XSG

**Comment by corsicanu** [comment]
@adel-2 Tested locally and it works, need @ananjaser1211 to test on his korean note, maybe it's related to that

**Comment by adel-2** [comment]
Thanks corsicanu will wait for other feedback from someone who has Korean version like mine N950N. Are you able to add Korean csc like LUC and KUC to the install selections? i will add it in a new suggestion post Thank you

**Comment by ananjaser1211** [comment]
Did you change the kernel ?
Tested hotspot on my N950N and it works just fine (I used XSG CSC)

**Comment by adel-2** [comment]
> Did you change the kernel ?
> Tested hotspot on my N950N and it works just fine (I used XSG CSC)

Thanks ananjaser1211, I didn't change the kernel. I tried XSG like you suggested but same issue. Hotspot connects but no internet. I also tried KOO csc but same issue. 
I am using ATT sim card. When I flash my N950N back to v12 ROM, LUC csc it works like a charm.

To further test. I flashed v12 this time with XSG csc since I couldn't get KOO to try as well. I get the same issue Hotspot connects without internet. I am starting to believe that I need LUC csc to have my phone work fine with ATT. Where can I get LUC csc file to flash for testing? Is that possible? Or could it be kernel related that conflict with my provider?
I will be happy to test if anyone have other kernel or LUC or KTC csc. Thanks

**Comment by ananjaser1211** [comment]
> > Did you change the kernel ?
> > Tested hotspot on my N950N and it works just fine (I used XSG CSC)
> 
> Thanks ananjaser1211, I didn't change the kernel. I tried XSG like you suggested but same issue. Hotspot connects but no internet. I also tried KOO csc but same issue.
> I am using ATT sim card. When I flash my N950N back to v12 ROM, LUC csc it works like a charm.
> 
> To further test. I flashed v12 this time with XSG csc since I couldn't get KOO to try as well. I get the same issue Hotspot connects without internet. I am starting to believe that I need LUC csc to have my phone work fine with ATT. Where can I get LUC csc file to flash for testing? Is that possible? Or could it be kernel related that conflict with my provider?
> I will be happy to test if anyone have other kernel or LUC or KTC csc. Thanks

since you flashed V12 pie with XSG and had no hotspot, it does seem like your carrier has some configs related to that. which is quite weird to be honest.

in this case it seems that i need to add KTC. 

its not really easy as just a flashable so you will have to wait for the next release

you can ignore my comment on the other thread about csc affecting hotspot, as this is news to me

**Comment by adel-2** [comment]
Since it is not an easy flashable I understand. I will continue using V12 till your next realease. I will also continue to test with other csc and even repeat experimenting with same and report back here if any success. Thank you for addressing it.

**Comment by adel-2** [comment]
I experimented with v12 older ROM. The csc that allowed me to use hotspot successfully on my N950N w/ ATT sim are LUC, KTC and BTU (surprisingly). But when using BTU with Qv1.0 ROM it doesn't work.
I tested ATT, XSG in both ROMs but no internet sharing!
