### ISSUE TITLE
[BUG] Status Bar button grid

### ISSUE THREAD

**Issue by crankycracker** [ananjaser1211/hadesRom_Reports#51]
**Description**
First of all, thanks for the rom, its great. I'm not sure if this is a bug or not. On One UI 1.0 i got used to the 5x3 button grid in status bar. Now it's 4x4 in One UI 2.5, which is good, because we have 1 more button in one page. On the other hand it is strange for me, because the buttons are so much bigger. If there were on option to make it 5x4 would be amazing, because i use frequently these buttons. So my question is that this feature has been removed in the rom, or there is no option in the original One UI 2.5 neither.
I also tried to search for it in different setting options, but without any success.

I know that it's not a big deal, and i will probably get used to it, if there is no solution, but it pierces my eyes every time i use the status bar.

**To Reproduce**
Pull down status bar, and open the 3 dot menu.

**Screenshots**

One UI 1.0

![Capture](https://user-images.githubusercontent.com/77162031/104045745-4b6e2a80-51df-11eb-9898-085a75da199c.PNG)

One UI 2.5

![Screenshot_20210108-180147_One UI Home](https://user-images.githubusercontent.com/77162031/104045807-6476db80-51df-11eb-910b-34a1e54a1697.jpg)

**Smartphone:**
 - Device: Galaxy S8
 - Model: G950F

**Comment by ananjaser1211** [comment]
Button grid has been removed in one 2.0 and up. I'm not aware of any other ways to change grid manually. I know it automatically resizes to 3x4 i think when you use dualism but thats about it

**Comment by corsicanu** [comment]
@ananjaser1211 In OneUI 3.0 they added grid change in recently updated QuickStar module but i'm not sure it does same thing for 2.*

**Comment by SypeR54** [comment]
@corsicanu I can confirm on OneUI 2.1, updated QuickStar not restore the statusbar grid option. However, when i check the changelog and screenshots it seems like OneUI 3.x only feature.

https://www.androidpolice.com/wp-content/uploads/2020/12/11/Screenshot_20201211-115859_QuickStar.png
https://www.androidpolice.com/wp-content/uploads/2020/12/11/Screenshot_20201211-115923_QuickStar.png

**Comment by crankycracker** [comment]
Yes i also tried QuickStar, but it doesn't have the option. Thanks for the information!
