### ISSUE TITLE
[Feature] Request to add Korean csc LUC

### ISSUE THREAD

**Issue by adel-2** [ananjaser1211/hadesRom_Reports#52]
**Describe the feature**
older version v12 had LUC csc. Can you please add it to the new Q v1.0

**Comment by ananjaser1211** [comment]
@adel-2 For Korean csc. Select KOO. It is unbranded Korean csc (similar to LUC KTC etc)

Based on tests I've done with other Korean testers. Instead of adding 3 regions. 1 works just as well

**Comment by adel-2** [comment]
> @adel-2 For Korean csc. Select KOO. It is unbranded Korean csc (similar to LUC KTC etc)
> 
> Based on tests I've done with other Korean testers. Instead of adding 3 regions. 1 works just as well

Thanks ananjaser1211. I  tried KOO csc but hotspot still doesn't deliver internet. 
I looked for KOO csc in v12 ROM to test it but didn't see it there. In v12 I flashed with LUC and on another try with KTC and they both worked like a charm. 
BTW I tested XSG csc with v12 Rom and gave same Hotspot issue. 

Conclusion: My N950N , ATT sim, V12 ROM
Hotspot works succesfully only if selecting LUC or KTC

**Comment by ananjaser1211** [comment]
@adel-2 But the thing is. Hotspot should not be related to your csc anyway..

**Comment by adel-2** [comment]
I thought so too but it apears to affect it. I will retest again with same and csc with v12 since i know 2 korean csc LUC and KTC are good. I didn't spend much time trying others except for one time trying XSG. I will do more testing to rule out the odd one time issues. Thank you
