### ISSUE TITLE
[BUG] Hotspot always 2.4Ghz even while choosing 5Ghz

### ISSUE THREAD

**Issue by AMasrar** [ananjaser1211/hadesRom_Reports#54]
**Describe the bug**
Hotspot 5Ghz is not working, although choosing the 5ghz band the created hotspot is just using 2.4ghz band

**To Reproduce**
1. Start Hotspot with 5Ghz option
2. Verify the band of the created Hotspot in another device

**Smartphone (please complete the following information):**
 - Device: Galaxy S8+
 - Model: G955F

**Comment by sabricanozkznc** [comment]
If you are using the Wi-Fi repeat mode, this works at 2.4 GHz. If you share with mobile data, it works at 5 GHz.
At first I thought 5 GHz was not working, but that's the case I'm using Note 8 by the way.

**Comment by ananjaser1211** [comment]
@sabrican244 Sharing my mobile data works in 5G mode.

Sharing wifi however is 2.4G

I tested it on my note 8 (with hades) and my S9+ (stock rom)

Probably 5ghz band is busy.

**Comment by AMasrar** [comment]
@ananjaser1211 I tried it with mobile data it's always 2.4GHz, I event went a step further and disabled the sharing wifi option same thing. In the stock rom the 5GHz option was not available for me (regional restrictions) maybe that has something to do with it? Can it be bypassed with CSC customizations? Any suggestions.

**Comment by ananjaser1211** [comment]
some countries do not let you change band from 2.4/5 in hotspot, this restriction however is already bypassed in the rom. hence why you can see the option.

not sure really why its not working on your end, the restriction only hides the settings for band options

will wait to see if others have this issue or not

**Comment by sabricanozkznc** [comment]
<img width="284" alt="Ekran Resmi 2021-01-13 11 21 13" src="https://user-images.githubusercontent.com/8625875/104425817-2c321d00-5592-11eb-9167-20b8ff1ed40d.png">


![Screenshot_20210113-112101_Settings](https://user-images.githubusercontent.com/8625875/104426262-c4c89d00-5592-11eb-9822-f289118eb8dc.jpg)


Here is my settings and 5 GHz working very well. Note 8 Hades Q v1

**Comment by Zeffuro** [comment]
For what it's worth, this also happens on stock rom.
A workaround that worked for me was using an app called WiFi Band that has a prefer 5 GHz option.

**Comment by AMasrar** [comment]
I did take a look at the WiFi Band app, it seems that it has to do with connecting to a 5Ghz network not creating a 5Ghz hotspot.

> For what it's worth, this also happens on stock rom.
> A workaround that worked for me was using an app called WiFi Band that has a prefer 5 GHz option.

**Comment by Zeffuro** [comment]
Ahhh my bad, I was browsing the issues contemplating to flash this rom soon and I completely read over the hotspot word in the title and description. Sorry about that!

**Comment by ananjaser1211** [comment]
Closing this as it seems to be working as expected, ive had shoddy "5G Hotspot" on my S9 running stock, if you are using the 5G band it will not create a 5g hotspot, seems to be the case on my S9 , N8 and S7.

i can create a 5G network if i am using mobile data, i.e wifi is not being used
