### ISSUE TITLE
[BUG] No Hades Boot Animation.

### ISSUE THREAD

**Issue by Iaotle** [ananjaser1211/hadesRom_Reports#55]
**Describe the bug**
Selecting Hades boot animation instead results in static samsung logo on boot.

**Smartphone (please complete the following information):**
 - Device: Galaxy S8+

**Comment by mdsarfaraj76** [comment]
I have also this problem..
Device:S8+
Model:g955n

**Comment by ananjaser1211** [comment]
this along side other boot animation issues will be resolved in the next version
