### ISSUE TITLE
[BUG] save conf of the phone

### ISSUE THREAD

**Issue by juuushiro** [ananjaser1211/hadesRom_Reports#57]
**Describe the bug**
Describe your issue here. 

**To Reproduce**
1. Go to dev options 
2. Click on change min with 420 change to 560
3. Change the power mode
4. See and and check the settings is not save, 

**Expected behavior**
A clear description of what you expected to happen.
Settings be safe, for next , and in Goodluck same issues
 - Model: [e.g. G950F]

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by ananjaser1211** [comment]
And this did not happen before ?? this is intended behavior as changing power mode changes your screen resolution.
which changes whatever dpi you have set in developer options.
