### ISSUE TITLE
WLAN not working continuously [BUG]

### ISSUE THREAD

**Issue by Montiburn213** [ananjaser1211/hadesRom_Reports#58]
**Describe the bug**
Describe your issue here. 

My WLAN is not working continuously. It seems like its going into "Sleep-Mode". Cant find any setting to change it. After switching to 4G its working often but also not always. After reboot its fine for a while,

e.g. WhatsApp is "offline" after the Night. First after opening messages are incoming. Or my Xiaomi Cams cant reach them. Have to reboot the Phone.

**Smartphone (please complete the following information):**
 - Device: Galaxy S8 (on Windows 10 showing Galaxy Note9)
 - Model: G950F Germany

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable
Not sure which Log is needed. Can deliver in addiotion if needed.

**Comment by ananjaser1211** [comment]
N950N All good here. Instant msgs shows up directly
