### ISSUE TITLE
[BUG] Dual speaker + Dolby Atmos make earpiece sizzle

### ISSUE THREAD

**Issue by le3e** [ananjaser1211/hadesRom_Reports#6]
**Describe the bug**
If you use dual speaker + dolby Atmos(in any option) and put the sound in max, the earpice will sizzle

**To Reproduce**
1. Select dual speaker in aroma
2. Enable dolby atmos in settings
3. Put the song in max volume
4. Play a music
5. Listen to the sizzle in the earpice

**Expected behavior**
Earpice to sizzle

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S8]
 - Model: [e.g. G950F]

**Additional context**
not applicable

**Comment by corsicanu** [comment]
This happens because of volume being too loud, will be addressed for next release.
As a workaround lower earpiece gains from hKtweaks app, sound options.

Leaving it open for visibility.

**Comment by corsicanu** [comment]
Will be fixed in next release, leaving it open for visibility.
