### ISSUE TITLE
[BUG] No sound on DEX mode connected via HDMI

### ISSUE THREAD

**Issue by szjarosz** [ananjaser1211/hadesRom_Reports#60]
**Describe the bug**
No sound on DEX mode connected by HDMI wire.

**Expected behavior**
No sound when you connect phone with tv via hdmi cable.
Tested with original dex station and adapter USBC-HDMI.
Tested also in both modes: dex and mirror.

**Smartphone**
 - Device: [Galaxy S8]
 - Model: [G950F]

**Comment by ananjaser1211** [comment]
I found the bug while trying to fix something else, ill keep the error here so i dont forget about it

`2021-01-18 08:53:28.669 4106-4177/? E/vndksupport: Could not load /vendor/lib/hw/audio.usb.default.so from default namespace: dlopen failed: cannot locate symbol "profile_get_highest_sample_rate" referenced by "/system/vendor/lib/hw/audio.usb.default.so"....`

**Comment by Terryss95** [comment]
Does this problem still occur?

**Comment by ananjaser1211** [comment]
should be fixed in v2, please report if otherwise
