### ISSUE TITLE
[BUG] Camera HEIF option is not work

### ISSUE THREAD

**Issue by huahuasousou** [ananjaser1211/hadesRom_Reports#62]
**Describe the bug**
I found a Bug that, in the camera setting option, after enabled HEIF option, the photo still is jpg format. I think is not work but android 10 is support HEIC format and S8 8895 can recording HEVC format video, I think maybe have some way can fixed it?
**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S8]
 - Model: [e.g. G950F]

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by ananjaser1211** [comment]
option was not supposed to be in the camera anyway, will be removed. HEIF is not available on my S9 with Q,
