### ISSUE TITLE
Android Auto use causes instant restart of phone, until Android Auto is deactivated on vehicle[BUG]

### ISSUE THREAD

**Issue by KampkH** [ananjaser1211/hadesRom_Reports#64]
**Describe the bug**
The issue I have encountered is that whenever i have android auto activated on my vehicle which prompts the phone to load up the Application, it causes the phone to just restart. I have tried several different methods to make it work, installed older versions of the Android Auto software, used different high quality wires but the only way that i am able to stop the instant restart is by deactivating the app on my vehicle. I have used a stock rom S6 Edge that is rooted with the vehicle and the software works flawlessly. On the prior ROM (horizon rom UI 1.5) i had installed on the phone, the app was also working, so I can only assume that either Android 10 is not optimised for the App, or there's just a bug in the system. I understand that there are many problems with the Android Auto software already so that doesn't help either, however for it to work on older ROMs and now not, I thought it was an issue worth noting.

**To Reproduce**
1. Activate Android Auto vehicle. (Have any version of Android Auto on the phone installed)
2. Plug phone into the vehicle and wait for 'connect via Android Auto prompt' on vehicle.
3. Accept the prompt to connect via Android Auto
4. See error as phone restarts instantly and keeps restarting until wire is unplugged.

**Expected behavior**
The phone should connect to the vehicle as it has on prior custom ROMs and stock ROMs, essentially projecting the App onto the vehicle screen, giving access to Google Maps, Music, Calendar and other options available. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S8 Plus
 - Model: G955F Duos

**Additional context**
Logs
The latest attempt using the latest update of the Android Auto app and a high quality wire was at 12:53pm, 29th January as seen on the log. I hope this can somewhat help.
[log_e.log](https://github.com/ananjaser1211/hadesRom_Reports/files/5894468/log_e.log)

**Comment by KampkH** [comment]
Just received a new Anker wire that when used has now somehow stopped the spontaneous restarts. Now it shows that the phone is connected to the vehicle but the car screen doesn't show anything. However that seems to be a common problem with Android Auto.

**Comment by Snowers96** [comment]
I have a C3 that work with AA and work as expected

**Comment by ananjaser1211** [comment]
Any more updates on this ? is it a ROM issue, or a peripheral issue, i do not have AA enabled car to test

**Comment by Snowers96** [comment]
> Any more updates on this ? is it a ROM issue, or a peripheral issue, i do not have AA enabled car to test

Well on my C3 almost everything works well. But for example BT calls with android auto are very bad, but if i make a call with whatsapp they work fine.
Also, i tried Spotify and works very well

**Comment by ananjaser1211** [comment]
> > Any more updates on this ? is it a ROM issue, or a peripheral issue, i do not have AA enabled car to test
> 
> Well on my C3 almost everything works well. But for example BT calls with android auto are very bad, but if i make a call with whatsapp they work fine.
> Also, i tried Spotify and works very well
The bluetooth bug is related to another issue here #13 

so when we fix that it should be fixed with AA too
