### ISSUE TITLE
[BUG] Fortnite does not work

### ISSUE THREAD

**Issue by bloodyErik** [ananjaser1211/hadesRom_Reports#65]
Matchmaking crashes when droping from the bus. The game said that they kicked me out because of my VPN, IP-adress etc.

**To Reproduce**
1. Go to Fortnite
2. Click on Start (Matchmaking)
3. Drop from the bus
 - Device: [Galaxy S8 Plus]
 - Model [G955FD]

**Comment by ananjaser1211** [comment]
@bloodyErik This is magisk hide related. The rom comes with basic safety net bypasses. Some apps including fornite need alot more to work. You can find guides online that may or may not work. But this is out of the scope of this rom

**Comment by bloodyErik** [comment]
> @bloodyErik This is magisk hide related. The rom comes with basic safety net bypasses. Some apps including fornite need alot more to work. You can find guides online that may or may not work. But this is out of the scope of this rom

ok, thanks

**Comment by bloodyErik** [comment]
ok, thanks

**Comment by bloodyErik** [comment]
i have read about this on xda and there was written that i should turn off the oem unlock, but i can't because you have removed this option from developer settings. It said that oem unlock can be turned off via adb. Will it be ok if i turn this off?

**Comment by ananjaser1211** [comment]
@bloodyErik Of course not. Turning off oem unlock will brick the rom and require you to flash full stock again. Hence why the option to do so is removed.

Oem unlock off means your bootloader is locked and won't accept custom roms

**Comment by Snowers96** [comment]
With the latest bootloader you cant relock BL anymore

**Comment by ananjaser1211** [comment]
Closing this as its not an issue with the ROM itself, but Safetynet
