### ISSUE TITLE
[BUG] One Camera Working only on Note 8

### ISSUE THREAD

**Issue by shinryuken3000** [ananjaser1211/hadesRom_Reports#66]
When using camera on Note 8, only one camera can be used. Could anyone fix? Thank you.
![141971-phones-feature-samsung-galaxy-note-8-camera-image1-heo2cwymdp](https://user-images.githubusercontent.com/77060184/106473846-dab4e800-64d6-11eb-9773-a4f469680f31.jpg)

**Comment by ananjaser1211** [comment]
@shinryuken3000 Both cameras are working in photo and video. The telephoto camera turns on when there is enough light and at 2.4x zoom level (not 2.0x)

This is related to another bug mentioned in this issues page
