### ISSUE TITLE
[BUG] MTP files transfer

### ISSUE THREAD

**Issue by AMasrar** [ananjaser1211/hadesRom_Reports#70]
**Describe the bug**
MTP is not working i can see my files but as soon as I start a transfer the device disconnect and shows this error "A device attached to the system is not functioning", tried with diffrent cables and with other computers same thing. It does work normal in TWRP.

**To Reproduce**
Start a transfer from or to the phone with MTP.

**Smartphone (please complete the following information):**
 - Device: Galaxy S8+ 
 - Model: G955F

**Comment by ananjaser1211** [comment]
All good on my device, usually that error happens when MTP is "busy" i.e your phone is doing something such as DEX , LinkToPC And such
