### ISSUE TITLE
[BUG]Camera opens slow in snapchat insta and WhatsApp 

### ISSUE THREAD

**Issue by ennu04** [ananjaser1211/hadesRom_Reports#73]
**Camera opens slow in snapchat WhatsApp Instagram**
Describe your issue here. 

**To Reproduce**
Go to Snap insta or WhatsApp and open camera it takes way to long or glitches out 

**Expected behavior**
Start faster than this 

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S8+]
 - Model: [e.g. SM-G955f

**Comment by Snowers96** [comment]
Instagram too

**Comment by alienflorina** [comment]
On instagram not only does freeze on camera but sometimes while watching stories too

**Comment by ananjaser1211** [comment]
i think this is related to #17 

will see with v2

**Comment by ennu04** [comment]
when will v2 come out?

**Comment by corsicanu** [comment]
@ennu04 never
