### ISSUE TITLE
[BUG] Battery overheat on Q v1 but on pie battery is stable

### ISSUE THREAD

**Issue by twinnybloggers** [ananjaser1211/hadesRom_Reports#75]
I have issue about battery when im using Q v1 . But on pie battery is stable ... any suggest how to fix this ? 
I have buying new battery but draining fast and my phone is hot ?

Any suggest how to do ? ..
Thanks 

 - Device: [e.g. Galaxy S8]
 - Model: [e.g. G950F]

**Comment by ananjaser1211** [comment]
you dont really give alot of information, Q gives me around 5hours to 6 hours sometimes on normal usage with social apps etc. your battery is either too degraded or you did not give the rom enough time to stabilize

**Comment by twinnybloggers** [comment]
> you dont really give alot of information, Q gives me around 5hours to 6 hours sometimes on normal usage with social apps etc. your battery is either too degraded or you did not give the rom enough time to stabilize

thanks for reply.  btw  any suggest for hktweaks ? or this issue problems with magisk v21?
