### ISSUE TITLE
[BUG] Intelligent Features on Camera app not present.

### ISSUE THREAD

**Issue by Beanosaur2** [ananjaser1211/hadesRom_Reports#76]
**Describe the bug**
Intelligent Features not available on the camera app,
but were present in Pie camera.

**To Reproduce**
1. Go to Camera
2. Click on Settings
3. Scroll down to Intelligent Features
4. The Intelligent Features page is not present, so I am unable to scan QR Codes and stuff.

**Expected behavior**
On Android 9, the Intelligent Features page will be there and will allow you to scan QR Codes, etc
(Basically like Bixby Vision, but its integrated to the main camera)

**Screenshots**
![Uploading WhatsApp Image 2021-02-26 at 10.14.24 PM.jpeg…]()

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S8+]
 - Model: [e.g. G955F]

**Comment by ananjaser1211** [comment]
This is no longer a thing in Q with corev1 camera devices. it all goes through bixby vision manually. and you cant run pie camera apk reliably.
