### ISSUE TITLE
[BUG] Bixby Vision doesn't work occasionally.

### ISSUE THREAD

**Issue by JizzleDaiiz** [ananjaser1211/hadesRom_Reports#77]
**Describe the bug here**
1. Bixby Vision doesn't work and produces a green screen upon launch and requires force closing and opening the app again for it to work, sometimes it freezes up the phone and requires a hard restart.

**To Reproduce**
Steps to reproduce the behavior (Bixby Vision):
1. Go to Galaxy Store and download Bixby Vision 
2. Launch the app
3. Green screen appears and phone freezes up.
**Screenshots**
![Screenshot_20210227-113713_Bixby Vision](https://user-images.githubusercontent.com/79734947/109374620-9cea8a00-78f1-11eb-83e9-eb25a2410461.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S8+
 - Model: SM-955F

Edit: Headphones static bug was addressed by dev in another bug report. Sorry.

**Comment by JizzleDaiiz** [comment]
I require the QR Code scanner because in my country we require it in order to scan QR codes for safety measures with regards to Covid-19.

**Comment by ananjaser1211** [comment]
Get logs when this happens next time

**Comment by JizzleDaiiz** [comment]
noted, thanks.

**Comment by ananjaser1211** [comment]
Thank you

**Comment by corsicanu** [comment]
> I require the QR Code scanner because in my country we require it in order to scan QR codes for safety measures with regards to Covid-19.

Playstore has some good QR scanners, your country doesn't require Samsung native feature, you can scan codes with anything at hand. For example, before QR scanner became a native thing in camera or bixby i used to use this app: https://play.google.com/store/apps/details?id=com.qrcodereaderpro

**Comment by ananjaser1211** [comment]
This should be fixed in V2
