### ISSUE TITLE
[BUG] Youtube not saving history, fav vids etc.

### ISSUE THREAD

**Issue by MohamedZaoui1** [ananjaser1211/hadesRom_Reports#78]
**Describe the bug**
De
 - Device: [e.g. Galaxy Note 8]
 - Model: [e.g. N950F]
hadesRom_Q_OneUI_v1.0_8895-FTK3

**Comment by corsicanu** [comment]
@MohamedZaoui1 disable adaway or any kind of adblock and try again

**Comment by corsicanu** [comment]
@MohamedZaoui1 also next time try to respect the issue layout and be brief

**Comment by MohamedZaoui1** [comment]
You have selected the adblocker not resolving the Medication I used an older version of YouTube, and now things are good
