### ISSUE TITLE
[ISSUE] Dex closes app even though it's not overheating

### ISSUE THREAD

**Issue by Ace2RA** [ananjaser1211/hadesRom_Reports#79]
**Describe the bug**
Are there any way to disable "apps close when overheating" function? It's really hard to use dex if it closes apps when I'm using it even though it's not really overheating.

**To Reproduce**
Play any games (Genshin Impact, COD, Pubg)

 - Device: Galaxy S8
 - Model: G955F

**Comment by ananjaser1211** [comment]
I am not sure DexOnPC is designed for games, using it with normal apps like telegram , chrome never showed that pop-up, however if i lunch a game it overheats (Happens on my S9 too)
