### ISSUE TITLE
[BUG] Ringtone/Notification SoundTheme Selector Broken

### ISSUE THREAD

**Issue by SypeR54** [ananjaser1211/hadesRom_Reports#8]
**Describe the bug**
In Settings > Audio > Notification and Ringtone selection there is 4 Sound Theme provided. However in /system/media/audio folder has only 1 SoundTheme (which is the default Theme) called "Galaxy" theme with distributed files. 

**To Reproduce**
1. Go to 'Settings > Audio > Notification and Ringtone'.
2. Click on any other Theme except 'Galaxy' theme.
3. See error

**Expected behavior**
Normally it should be show the ringtone list as expected on other sound themes.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy X8(+)
 - Model: X950X

**Additional context**
- No needed. S20/N20 audio folder replacement should fix the issue.

**Comment by corsicanu** [comment]
Will be fixed in next release, leaving it open for visibility.
