### ISSUE TITLE
[BUG] Many apps crashing

### ISSUE THREAD

**Issue by vuthanho** [ananjaser1211/hadesRom_Reports#81]
**Describe the bug**
Recently, some of my apps were instantly crashing like outlook, microsoft teams, dealabs, chess tactics pro. Also, there was a weird behavior with dealabs for instance: the app would crash if I would have opened it normally, but if I would long press on the app to go into my notifications let's say, then no crash. Even weirder, since it was impossible to use my phone, I decided to report here the bug with a log with crashes. And... the fact of making a log fixed everything. I don't understand. Maybe it was just by pure luck and the bug will occur later. Anyway, I attached the log, maybe there's something in it.

**To Reproduce**
As mentioned above, I can't reproduce it anymore. 

**Smartphone:**
 - Galaxy S8
 - G950F
[log_e.log](https://github.com/ananjaser1211/hadesRom_Reports/files/6196605/log_e.log)

**Comment by corsicanu** [comment]
@vuthanho It’s not related to the rom, it’s because of google and it makes sense to get fixed by itself since they forcefully push a fix for it short time after it occured. See more here https://www.theverge.com/2021/3/22/22345696/google-android-apps-crashing-fix-system-webview
Regards.

**Comment by vuthanho** [comment]
Thank you!
