### ISSUE TITLE
[BUG]NET::ERR_CERT_AUTHORITY_INVALID  

### ISSUE THREAD

**Issue by ennu04** [ananjaser1211/hadesRom_Reports#82]
**Describe the bug**

Page dont load
**To Reproduce**
1. Go to Google 
2. Click on 'dosnt matter '

**Expected behavior**
A clear description of what you expected to happen.

Loading the web page 

**Screenshots**

![Screenshot_20210325-155412_One UI Home.jpg](https://user-images.githubusercontent.com/76682975/112493497-81ed2780-8d82-11eb-828e-ce602bc1a969.jpg)
![Screenshot_20210325-160347_Chrome.jpg](https://user-images.githubusercontent.com/76682975/112494954-bca38f80-8d83-11eb-9d9b-4ce0041bee11.jpg)
**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S8+]
 - Model: [e.g. G955F]

**Additional context**
Getting this on many pages 

Greetings from Germany 🇩🇪😀

**Comment by corsicanu** [comment]
@ennu04 Check your date/time settings, update all your apps, disable adblockers. This is not related to the rom.

**Comment by corsicanu** [comment]
@ennu04

**Comment by ennu04** [comment]
> @ennu04 Check your date/time settings, update all your apps, disable adblockers. This is not related to the rom.

Dont have Adblock and date / time is set to auto and is correctly

**Comment by ennu04** [comment]
Nvm my Phone crashed 3 Times and now its working 🤷‍♂️
