### ISSUE TITLE
DeX not working with a display dock or cable

### ISSUE THREAD

**Issue by KeithJackal** [ananjaser1211/hadesRom_Reports#85]
**Describe the feature**
Using Continuum dock (HD-500) on stock OneUI 1.0 DeX was functional with Note8 (also S10e works). After flashing the hades port it doesn't show up, same for Type-C to HDMI.

**Possible Visualization**
![PXL_20210522_014927130](https://user-images.githubusercontent.com/52633494/119205198-43cd6500-baa0-11eb-8953-805ebe0c9fab.jpg)

**Expected behavior**
Hooking up the phone I should get DeX on display and notification on mobile.

**Smartphone:**
 - Device: Galaxy Note 8
 - Model: N950F

**Origin of ROM**
https://forum.xda-developers.com/t/rom-10-hadesrom-q-v1-0-for-exynos-s8-s8-note8-26-12-2020.4208409/

**Comment by corsicanu** [comment]
It's hard to debug this type of problems, maybe an idea would be to try to log everything using mobile apps while connecting this spefic dock.
