### ISSUE TITLE
[Feature] Add the iris and camera feature and Samsung pay and Samsung pass. Change model number for note 8 

### ISSUE THREAD

**Issue by norepleyduc** [ananjaser1211/hadesRom_Reports#88]
Can you add the iris and camera feature and Samsung pay and Samsung pass.Change model number for note 8

**Comment by ananjaser1211** [comment]
Samsung pay and pass will never work on knox 0x1 devices, if you want those you need a new device and never root it.

Note 8 model is not used on ports, as it conflicts and breaks features, if you want that change the prop manually.

iris there is a bug here #1 . only note 8 iris is working for now.

**Comment by norepleyduc** [comment]
> Samsung pay and pass will never work on knox 0x1 devices, if you want those you need a new device and never root it.
> 
> Note 8 model is not used on ports, as it conflicts and breaks features, if you want that change the prop manually.
> 
> iris there is a bug here #1 . only note 8 iris is working for now.

And i bought a new s20fe

**Comment by SypeR54** [comment]
@hkduc Congrats for your new device. Now you can close your issue ticket. Thanks. 😊
