### ISSUE TITLE
[Feature]change the model number to note 8 not galaxy s9 +

### ISSUE THREAD

**Issue by norepleyduc** [ananjaser1211/hadesRom_Reports#90]
Can you change the model number to note 8 not galaxy s9 + in next version please

**Comment by corsicanu** [comment]
@hkduc It breaks features since Note 8 was never meant to receive Android 10, so the answer is no.. Also maybe you're in the wrong side of internet, our rom is based exclusively on N960F aka Note 9, not S9+ as you say...

**Comment by ananjaser1211** [comment]
https://github.com/ananjaser1211/hadesRom_Reports/issues/88#issuecomment-901028743

**Comment by norepleyduc** [comment]
![Screenshot_20210823-064927_Settings.jpg](https://user-images.githubusercontent.com/47637780/130374059-75741e0a-4afb-4a4d-b451-154cd291cc84.jpg)

**Comment by norepleyduc** [comment]
You can change the model number because when i open another app it shows galaxy s9+ not the galaxy note 9. I said you change the model number because this

**Comment by ananjaser1211** [comment]
Model is set to G965F in V1 to make safetynet work, V2 will have N960F, but neither will have note 8 model due to the issues mentioned in the earlier replies.

**Comment by norepleyduc** [comment]
If change the n9607 does we have the safenet

**Comment by ananjaser1211** [comment]
@hkduc on V1 no, on V2 yes, N960F will be default then

**Comment by norepleyduc** [comment]
Ok thank you can you open the donation please

**Comment by ananjaser1211** [comment]
@hkduc Donations for me or corsicanu can be found here https://forum.xda-developers.com/t/rom-10-hadesrom-q-v1-0-for-exynos-s8-s8-note8-26-12-2020.4208409/ in the personal thoughts section.

**Comment by hkduc** [comment]
Oke sorry i want ask when we have a v2

**Comment by ananjaser1211** [comment]
@hkduc i dont have an ETA in mind, but the expected release date is by the end of this month if development goes to plan

**Comment by norepleyduc** [comment]
Oke.It is on one ui 2.5 or 3

**Comment by corsicanu** [comment]
Oneui 5.2, can you stop at this point?

**Comment by ananjaser1211** [comment]
@hkduc 2.5, 3.x is not planned for this year, possibly next year
