### ISSUE TITLE
[BUG] fix goggle play and goggle play services

### ISSUE THREAD

**Issue by norepleyduc** [ananjaser1211/hadesRom_Reports#91]
Can you fix the goggle play and goggle play services sometime the goggle play install button can't be used to downloads

**Comment by corsicanu** [comment]
@hkduc Possible fixes for apps not installing:
- reboot
- wait more for Google to update itself (15-20 mins)
- manually update Play Store and Play Services to latest available on apkmirror.com and reboot
- clear Play Store and Play Services app data from Settings/Apps and reboot
- uninstall updates for Play Store and Play Services app data from Settings/Apps and reboot
- log off from Google account and login again and reboot

Try each and all of them, it will get fixed.

**Comment by norepleyduc** [comment]
If i hard restart my phone can fix it
