### ISSUE TITLE
[BUG]fix the config the bixby button

### ISSUE THREAD

**Issue by norepleyduc** [ananjaser1211/hadesRom_Reports#92]
When i go to the bixby key setting change the use double press then i double to the bixby jey it show like this ![Screenshot_20210824-181027_Bixby Voice.jpg](https://user-images.githubusercontent.com/47637780/130607036-34e9bf46-3ae7-44c6-8a4a-17782f6af987.jpg)

**Comment by ananjaser1211** [comment]
did you change bixby behavior in aroma ? (i.e selected the button to be used as shutter, or anything other than bixby)

**Comment by norepleyduc** [comment]
Oh thanks you
