### ISSUE TITLE
[BUG]OTG is not working?

### ISSUE THREAD

**Issue by menkhud** [ananjaser1211/hadesRom_Reports#93]
dont know what to write here.

**Comment by menkhud** [comment]
i have installed this rom 2 weeks ago yesterday when i plug(OTG with Pendrive) its not accessing the pendrive.

**Comment by SnowFuhrer** [comment]
wait a minute, I'll test on my note8

**Comment by SnowFuhrer** [comment]
Cant reproduce(note8 as i said though), can you provide screenshots and logs?

**Comment by menkhud** [comment]
i am new i dont know how to reproduce if you have video on it then tell me

**Comment by ananjaser1211** [comment]
OTG works just fine on my end and with testers using S8/S8+. might be bad cable, or badly formatted USB

**Comment by menkhud** [comment]
yeah it was .thank you.
