### ISSUE TITLE
[BUG] IRIS Lacks preview in enrollment/unlocking

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/hadesRom_Reports#96]
**Describe the bug**
Iris does not show black and white preview thing

**Expected behavior**
to see my beautiful eyes

**Screenshots**
just black box

**Smartphone (please complete the following information):**
- All models

**Additional context**
something something corev2 iris preview something

**Comment by shinryuken3000** [comment]
Hi
First of all, thanks a ton for your great rom.
Secondly, on my S8, I have the problem with Iris unlock. It's really hard and slow to unlock phone with Iris function. I have to move my S8 around but it's 50 50. 
If it is lucky to unlock at that position in front of my eye, I try to keep that position (my eye/face and S8), turn off the screen, open the screen to unlock again with Iris but fail (which should be successful).
What I tried (but fail): rebooting, removing and registerring Iris again.
Anyway, I use Face unlock instead, this function is still good
Hope this is helpfull
Thanks

**Comment by ananjaser1211** [comment]
Since iris has been thoroughly tested on all models, this is likely to be "bad" enrollment, not having a preview of your eye location does make it harder to get a proper enrollment, what i do on my note 8 is just so stare at the sensor while my phone is a bit far away (imagine selfie camera 16:9 mode, showing all your face in the frame)

and then open my eyes wide open, i dont wear glasses so thats also another variable. after enrollment it unlocks in less than a second. i would say just as fast as my S9+

**Comment by shinryuken3000** [comment]
Thanks for quick response. Yeah, I also stretch my eyes as I could, but still 50 50. I don't wear glasses, either. Also, try far or close distance. Registering is ok, but using is not good. But it's still good with Face and Fingerprint unlock 👍
I'll try with my Note8 (I have both S8 and Note8), I'm testing on S8 before my daily offical Note8.

**Comment by shinryuken3000** [comment]
After flashing, Iris on my Note8 works normally.

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue
