### ISSUE TITLE
[CRITICAL] GALAXY S8+ ONLY | ROM FIXUP | ANIMATION/EMOJIS And possibly more

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/hadesRom_Reports#97]
This is only for the S8+, i made a major mistake in the updater file that caused the system to be re-written to the device, possibly overwriting some aroma settings, this breaks animation selection (hades anim / stock pie anim) and might break emoji selection.

to fix this, download the `META-INF` linked below, and place it inside the root directory of the ROM.ZIP

[META-INF.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/7176459/META-INF.zip)

AKA, the file updater-script needs to go under this directory. you can either just place the META-INF folder inside the rom.zip directly, or copy the updater-script manually to the bottom location

`hadesRom_Q_OneUI_v2.0_8895-FUH1.zip/META-INF/com/google/android`

you can do this on your computer using winrar, 7zip (drag and drop) or on your device by unpacking the zip and repacking it (using FXExplorer or such)

since there are 7 mirrors of the ROM a reupload is quite hard for now, this will be bundled if we did a hotfix for the rom later in the future.

**Comment by corsicanu** [comment]
@ananjaser1211 delet dis
