### ISSUE TITLE
[BUG] Samsung Test Menu Not Working

### ISSUE THREAD

**Issue by Weldarvin** [ananjaser1211/hadesRom_Reports#98]
**Describe the bug**
Diagnostics menu not accessible. 
Only blank white screen when trying to access.

**To Reproduce**
1. Go to 'Dialer'
2. Type `'*#0*#'`
3.  See blank white screen instead of test options.

**Expected behavior**
A menu with buttons for various test options should be displayed

**Screenshots**

https://user-images.githubusercontent.com/2986886/133598997-94f9220c-3a4b-40b7-8936-f7f324234bf9.mp4

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 8
 - Model: N950F

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
