### ISSUE TITLE
[Feature] flashabale MOD to switch between torch and iris

### ISSUE THREAD

**Issue by AMasrar** [ananjaser1211/hadesRom_Reports#99]
**Describe the feature**
First, thanks for the new release. It could be a good idea to have the choice between the iris or the torch functionality. I don't want to sound ungrateful, but people needs are different many will appreciate iris, but also there is many others who never used it.

**Possible Visualization**
A flashable zip that gives you the choice between the iris feature or the torch

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device:  S8+

**Comment by corsicanu** [comment]
@AMasrar Though choice because it's not only that, the entire system is modded to behave as it has iris. 
On the other side making flashlight intensity work will also require rework of camera implementation to bring it back in the state of v1, which wasn't the best camera..
I'd say pass on this one.

**Comment by AMasrar** [comment]
I didn't think that it involves that much work. Well, I guess I just have to bite the bullet on this one.

**Comment by britshickhouse** [comment]
That's a shame, I'm with OP on this - adjustable torch is more important to me than iris.

Regardless, thank you for your hard work @corsicanu and team!

**Comment by ananjaser1211** [comment]
for now we will be setting the torch brightness to max (lvl5) in v2.1 , i might get to work on a custom kernel interface to control the flashlight level via hktweaks for example but that will have to wait for the next major release.

sadly setting a custom config for iris/torch will complicate the development process significantly
